"""
tab3_commit_lab.py — Tab 3: Commit Lab (Review, Lyrics Text Pipeline & Word Approval).
"""

import streamlit as st
import streamlit.components.v1 as components
import db
import pipeline
import prompt_builder
import gemini_client
from presentation.components.widgets import (
    render_domain_breakdown_section,
    load_nlp,
)
from presentation.components.session import sync_active_session


def render_tab_commit_lab():
    """Renders the Lyrics Analysis, Color-Coded Categorization, and Approval Pipeline."""
    st.subheader("🧪 Song Review, Text Pipeline & Word Approval")
    
    nlp = load_nlp()

    # Show commit success banner if a song was just saved
    if st.session_state.get("commit_success_message"):
        msg = st.session_state.commit_success_message
        st.balloons()
        song_num = msg.get("song_number")
        num_label = f"Song #{song_num}" if song_num else f"Song #{msg.get('song_id')}"
        st.success(
            f"🎉 **Song '{msg['title']}' Saved Successfully as {num_label}!**\n\n"
            f"- 🟢 **Target Words Approved:** {msg.get('target_count', 0)} words\n"
            f"- 🔵 **New Bonus NGSL Hits:** {msg.get('bonus_count', 0)} words (first time covered)\n"
            f"- ⚪ **Previously Covered Words Reused:** {msg.get('reused_count', 0)} words (usage counters incremented)\n"
            f"- 🟡 **Extra Non-NGSL Words:** {msg.get('extra_count', 0)} words\n\n"
            f"📊 **Progress Update:** **{msg['unused_remaining']:,}** words remain unused in NGSL (**{msg.get('total_used', 0):,}** words covered total)."
        )
        st.session_state.commit_success_message = None

    # Show active target words reminder
    if st.session_state.target_batch:
        current_target_words = [w["word"] for w in st.session_state.target_batch]
        target_display = ", ".join(f"`{w}`" for w in current_target_words)
        st.markdown(f"**Current 20 Target Words from Studio:** {target_display}")
    else:
        st.warning("⚠️ No active target batch loaded from Studio. If you analyze a song now, all detected NGSL words will be classified as Bonus hits (Blue), not Target hits (Green).")
        current_target_words = []

    st.markdown("Paste the final song lyrics generated by Suno AI / external LLM:")
    
    # Song Title with Mandatory Validation & Red Highlight
    has_title_error = st.session_state.get("title_has_error", False) and not (st.session_state.song_title_input or "").strip()
    title_label = "🎵 Song Title *(Required before approval)*" if has_title_error else "🎵 Song Title"
    
    st.session_state.song_title_input = st.text_input(
        title_label,
        value=st.session_state.song_title_input,
        placeholder="e.g. Echoes of the Horizon (Required to Approve & Save)",
        key="commit_song_title_input_field"
    )
    if st.session_state.song_title_input.strip() and st.session_state.get("title_has_error"):
        st.session_state.title_has_error = False

    if has_title_error:
        st.markdown(
            """
            <div id="title-error-banner" style="
                background: rgba(239, 68, 68, 0.12);
                border: 1px solid rgba(239, 68, 68, 0.4);
                border-radius: 8px;
                padding: 9px 14px;
                color: #EF4444;
                font-size: 0.88rem;
                font-weight: 700;
                margin-top: -6px;
                margin-bottom: 12px;
                display: flex;
                align-items: center;
                gap: 8px;
            ">
                <span style="font-size: 1.15rem;">⚠️</span>
                <span>لا يمكن اعتماد الأغنية بدون عنوان! يرجى كتابة عنوان الأغنية هنا أولاً (Song Title is required).</span>
            </div>
            <style>
            div[data-testid="stTextInput"]:has(input[aria-label*="Song Title"]) input,
            div[data-testid="stTextInput"]:has(input[placeholder*="Echoes"]) input {
                border: 2px solid #EF4444 !important;
                background-color: rgba(239, 68, 68, 0.08) !important;
                box-shadow: 0 0 0 4px rgba(239, 68, 68, 0.28) !important;
                animation: pulseTitleError 1.5s infinite alternate !important;
            }
            @keyframes pulseTitleError {
                from { box-shadow: 0 0 0 2px rgba(239, 68, 68, 0.2); }
                to { box-shadow: 0 0 0 6px rgba(239, 68, 68, 0.45); }
            }
            </style>
            """,
            unsafe_allow_html=True
        )
        components.html(
            """
            <script>
            setTimeout(() => {
                try {
                    const doc = window.parent.document;
                    const el = doc.querySelector('input[aria-label*="Song Title"]') || doc.querySelector('input[placeholder*="Echoes"]');
                    if (el) {
                        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
                        el.focus();
                        el.select();
                    }
                } catch(e) {
                    console.error("Focus error:", e);
                }
            }, 100);
            </script>
            """,
            height=0,
            width=0
        )
    
    st.session_state.raw_lyrics_input = st.text_area(
        "Song Lyrics",
        value=st.session_state.raw_lyrics_input,
        placeholder="Paste full lyrics including [Verse], [Chorus] tags here...",
        height=260
    )

    col_btn_analyze, _ = st.columns([1.5, 3])
    with col_btn_analyze:
        if st.button("🔍 Analyze Song", type="primary", use_container_width=True):
            if not st.session_state.raw_lyrics_input.strip():
                st.error("Please paste song lyrics before analyzing.")
            else:
                with st.spinner("Executing 5-step song processing pipeline..."):
                    lemma_map = db.get_all_lemma_mappings()
                    used_ngsl = db.get_used_ngsl_words()
                    results = pipeline.process_song_text(
                        raw_lyrics=st.session_state.raw_lyrics_input,
                        target_words=current_target_words,
                        lemma_to_headword=lemma_map,
                        nlp=nlp,
                        used_ngsl_words=used_ngsl
                    )
                    st.session_state.analysis_results = results
                    st.rerun()

    # Classification Report & Approval Form
    if st.session_state.analysis_results:
        res = st.session_state.analysis_results
        green_list = res.get("green", [])
        red_list = res.get("red", [])
        blue_list = res.get("blue", [])
        reused_list = res.get("reused", [])
        yellow_list = res.get("yellow", [])

        st.markdown("---")
        st.subheader("📊 Color-Coded Classification Report")
        
        m_col1, m_col2, m_col3, m_col4, m_col5 = st.columns(5)
        m_col1.metric("🟢 Target Hits", f"{len(green_list)} / {len(current_target_words)}")
        m_col2.metric("🔴 Missed Targets", f"{len(red_list)}")
        m_col3.metric("🔵 Bonus Hits (New)", f"{len(blue_list)}")
        m_col4.metric("⚪ Previously Covered", f"{len(reused_list)}")
        m_col5.metric("🟡 Extra Words", f"{len(yellow_list)}")

        # Song Vocabulary Domain Register Breakdown
        song_all_ngsl = list(set(green_list + blue_list + reused_list))
        song_domain_data = db.compute_domain_breakdown(song_all_ngsl)
        render_domain_breakdown_section(
            song_domain_data,
            title="🎯 Song Vocabulary Domain Register",
            compact=False
        )

        st.info("Uncheck any word below if you do NOT want it counted towards the database counters.")

        with st.form("approval_form"):
            rep_col1, rep_col2 = st.columns(2)

            with rep_col1:
                st.markdown(
                    f"""
                    <div class="report-card-green">
                        <h4>🟢 Target Hits ({len(green_list)})</h4>
                        <p><small>Target words found in song → will increment <code>usage_count</code>.</small></p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
                checked_green = []
                if green_list:
                    for w in green_list:
                        if st.checkbox(f"🟢 {w}", value=True, key=f"chk_green_{w}"):
                            checked_green.append(w)
                else:
                    st.caption("No target words detected in the lyrics.")

                st.markdown(
                    f"""
                    <div class="report-card-red">
                        <h4>🔴 Missed Targets ({len(red_list)})</h4>
                        <p><small>Target words not found in song → remains <code>usage_count = 0</code>.</small></p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
                if not current_target_words:
                    st.caption("No target batch was active during analysis.")
                elif red_list:
                    st.markdown(", ".join(f"`{w}`" for w in red_list))
                else:
                    st.success(f"🎉 Perfect! All {len(current_target_words)} target words were used in the song!")

            with rep_col2:
                st.markdown(
                    f"""
                    <div class="report-card-blue">
                        <h4>🔵 Bonus NGSL Hits ({len(blue_list)})</h4>
                        <p><small>New, previously unused NGSL words → will count as newly covered and increment <code>usage_count</code>.</small></p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
                checked_blue = []
                if blue_list:
                    for w in blue_list:
                        if st.checkbox(f"🔵 {w}", value=True, key=f"chk_blue_{w}"):
                            checked_blue.append(w)
                else:
                    st.caption("No newly introduced NGSL words found.")

                if reused_list:
                    reused_pills = " ".join(f'<span class="reused-pill">{w}</span>' for w in reused_list)
                    st.markdown(
                        f"""
                        <div style="background: rgba(148, 163, 184, 0.08); border: 1px solid rgba(148, 163, 184, 0.25); border-radius: 8px; padding: 12px; margin-bottom: 12px;">
                            <h4 style="margin: 0 0 4px 0; color: #94A3B8;">⚪ Previously Covered Words ({len(reused_list)})</h4>
                            <p style="margin: 0 0 8px 0;"><small style="color: #64748B;">NGSL words already introduced in past songs. Their global usage counter will update upon saving, but they are not counted as new bonus discoveries.</small></p>
                            <div>{reused_pills}</div>
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                st.markdown(
                    f"""
                    <div class="report-card-yellow">
                        <h4>🟡 Extra Words ({len(yellow_list)})</h4>
                        <p><small>Valid words not in NGSL → will be added/incremented in <code>extra_words</code>.</small></p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
                checked_yellow = []
                if yellow_list:
                    for w in yellow_list:
                        if st.checkbox(f"🟡 {w}", value=True, key=f"chk_yellow_{w}"):
                            checked_yellow.append(w)
                else:
                    st.caption("No extra non-NGSL words found.")

            pack_vocalist = st.session_state.get("selected_vocalist", "Male")
            st.markdown(
                f"""
                <div style="background: rgba(99, 102, 241, 0.08); border-left: 4px solid #6366F1; padding: 10px 14px; border-radius: 8px; margin: 12px 0 16px 0; font-size: 0.92rem; color: #E2E8F0;">
                    💿 <b>Packaging Integration:</b> When you approve, this song will automatically register its 
                    <b>Suno AI Music Style Prompt</b> and <b>Album Poster Prompt</b> under genre <b>{st.session_state.selected_genre}</b> ({pack_vocalist}) in your Songs Library!
                </div>
                """,
                unsafe_allow_html=True
            )

            st.markdown("---")
            submitted = st.form_submit_button("✅ Approve & Save Song", type="primary", use_container_width=True)
            
            if submitted:
                title = (st.session_state.song_title_input or "").strip()
                if not title:
                    st.session_state.title_has_error = True
                    st.toast("⚠️ برجاء كتابة عنوان الأغنية أولاً! تم نقلك لحقل العنوان.", icon="⚠️")
                    st.rerun()

                st.session_state.title_has_error = False

                mood_dict = st.session_state.mood_analysis.get("mood_breakdown", {}) if st.session_state.mood_analysis else {}
                current_genre = st.session_state.selected_genre
                current_structure = st.session_state.selected_structure
                current_concept = st.session_state.custom_concept.strip() or (
                    st.session_state.mood_analysis.get("creative_concept", "") if st.session_state.mood_analysis else ""
                )

                song_id, approved_ngsl_count, approved_extra_count = db.approve_and_save_song(
                    title=title,
                    lyrics=st.session_state.raw_lyrics_input.strip(),
                    target_words=current_target_words,
                    checked_bonus_words=checked_blue,
                    checked_extra_words=checked_yellow,
                    checked_target_words=checked_green,
                    reused_words=reused_list,
                    mood_breakdown=mood_dict,
                    genre=current_genre,
                    song_structure=current_structure,
                    creative_concept=current_concept
                )

                current_vocalist = st.session_state.get("selected_vocalist", "Male")
                saved_suno = (st.session_state.get("studio_suno_prompt") or "").strip()
                if not saved_suno:
                    saved_suno = prompt_builder.build_suno_style_prompt(current_genre, current_vocalist)

                saved_poster = (st.session_state.get("studio_poster_prompt") or "").strip()
                if saved_poster:
                    saved_poster = (
                        saved_poster
                        .replace("[Song Title]", title)
                        .replace("Your Song Title", title)
                        .replace("Untitled Song", title)
                    )
                else:
                    saved_poster = gemini_client.generate_studio_poster_prompt(
                        concept=current_concept or title,
                        genre=current_genre,
                        vocalist=current_vocalist,
                        title=title
                    )

                db.save_track_variant(
                    song_id=song_id,
                    genre=current_genre,
                    vocalist=current_vocalist,
                    suno_prompt=saved_suno,
                    poster_prompt=saved_poster
                )

                new_stats = db.get_progress_stats()

                db.save_studio_draft(
                    song_title=title,
                    batch=list(st.session_state.target_batch),
                    concept=current_concept,
                    genre=current_genre,
                    song_structure=current_structure,
                    mood_analysis=st.session_state.mood_analysis,
                    master_prompt=st.session_state.get("master_prompt", ""),
                    suno_prompt=st.session_state.get("studio_suno_prompt", ""),
                    poster_prompt=st.session_state.get("studio_poster_prompt", ""),
                    vocalist=current_vocalist,
                )

                st.session_state.target_batch = []
                st.session_state.mood_analysis = None
                st.session_state.master_prompt = ""
                st.session_state.studio_suno_prompt = ""
                st.session_state.studio_poster_prompt = ""
                st.session_state.custom_concept = ""
                st.session_state.analysis_results = None
                st.session_state.raw_lyrics_input = ""
                st.session_state.song_title_input = ""
                st.session_state.title_has_error = False
                db.clear_active_batch_state()

                all_saved_df = db.get_all_songs()
                real_song_num = len(all_saved_df)

                st.session_state.commit_success_message = {
                    "title": title,
                    "song_number": real_song_num,
                    "song_id": song_id,
                    "target_count": len(checked_green),
                    "bonus_count": len(checked_blue),
                    "reused_count": len(reused_list),
                    "extra_count": len(checked_yellow),
                    "unused_remaining": new_stats["unused"],
                    "total_used": new_stats["used"]
                }
                st.rerun()
